<a href="https://colab.research.google.com/github/sanjana-budha/prinston-internship/blob/main/indian_liver_patient_project_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#indian liver patient project

1.import numpy and pandas

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report, accuracy_score

In [ ]:
df= pd.read_csv("/content/indian_liver_patient 2.csv")

In [ ]:
df.head()

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
0,65,Female,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,Male,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,Male,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,Male,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,Male,3.9,2.0,195,27,59,7.3,2.4,0.40,1

In [ ]:
df.tail()

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
578,60,Male,0.5,0.1,500,20,34,5.9,1.6,0.37,2
579,40,Male,0.6,0.1,98,35,31,6.0,3.2,1.10,1
580,52,Male,0.8,0.2,245,48,49,6.4,3.2,1.00,1
581,31,Male,1.3,0.5,184,29,32,6.8,3.4,1.00,1
582,38,Male,1.0,0.3,216,21,24,7.3,4.4,1.50,2

In [ ]:
print(df.shape)

(583, 11)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         583 non-null    int64
 1   Gender                      583 non-null    object
 2   Total_Bilirubin             583 non-null    float64
 3   Direct_Bilirubin            583 non-null    float64
 4   Alkaline_Phosphotase        583 non-null    int64
 5   Alamine_Aminotransferase    583 non-null    int64
 6   Aspartate_Aminotransferase  583 non-null    int64
 7   Total_Protiens              583 non-null    float64
 8   Albumin                     583 non-null    float64
 9   Albumin_and_Globulin_Ratio  578 non-null    float64
 10  Dataset                     583 non-null    int64
dtypes: float64(5), int64(5), object(1)
memory usage: 50.2+ KB

In [ ]:
df.describe()

,Age,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
count,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,578.000000,583.000000
mean,44.746141,3.298799,1.486106,290.576329,80.713551,109.910806,6.483190,3.141852,0.947318,1.286449
std,16.189833,6.209522,2.808498,242.937989,182.620356,288.918529,1.085451,0.795519,0.319810,0.452490
min,4.000000,0.400000,0.100000,63.000000,10.000000,10.000000,2.700000,0.900000,0.300000,1.000000
25%,33.000000,0.800000,0.200000,175.500000,23.000000,25.000000,5.800000,2.600000,0.700000,1.000000
50%,45.000000,1.000000,0.300000,208.000000,35.000000,42.000000,6.600000,3.100000,0.940000,1.000000
75%,58.000000,2.600000,1.300000,298.000000,60.500000,87.000000,7.200000,3.800000,1.100000,2.000000
max,90.000000,75.000000,19.700000,2110.000000,2000.000000,4929.000000,9.600000,5.500000,2.800000,2.000000

2. checking null values

In [ ]:
df.isna().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    5
Dataset                       0
dtype: int64

In [ ]:
df1 = df.copy(deep=True)
df1.isna().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    5
Dataset                       0
dtype: int64

3. removing null values

In [ ]:
df1["Albumin_and_Globulin_Ratio"].fillna(1.5 ,inplace=True)
df1.head(15)

/tmp/ipython-input-10-341031532.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["Albumin_and_Globulin_Ratio"].fillna(1.5 ,inplace=True)

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
0,65,Female,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,Male,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,Male,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,Male,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,Male,3.9,2.0,195,27,59,7.3,2.4,0.40,1
5,46,Male,1.8,0.7,208,19,14,7.6,4.4,1.30,1
6,26,Female,0.9,0.2,154,16,12,7.0,3.5,1.00,1
7,29,Female,0.9,0.3,202,14,11,6.7,3.6,1.10,1
8,17,Male,0.9,0.3,202,22,19,7.4,4.1,1.20,2
9,55,Male,0.7,0.2,290,53,58,6.8,3.4,1.00,1
10,57,Male,0.6,0.1,210,51,59,5.9,2.7,1.50,1
11,72,Male,2.7,1.3,260,31,56,7.4,3.0,0.60,1
12,64,Male,0.9,0.3,310,61,58,7.0,3.4,0.90,2
13,74,Female,1.1,0.4,214,22,30,8.1,4.1,1.00,1
14,61,Male,0.7,0.2,145,53,41,5.8,2.7,0.87,1

In [ ]:
df1.isna().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    0
Dataset                       0
dtype: int64

4. value count of gender

In [ ]:
df["Gender"].value_counts()

Gender
Male      441
Female    142
Name: count, dtype: int64

# 5. Label Encoder converting string to numarical values

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df1.Gender = le.fit_transform(df1.Gender)
df1.head(10)

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
0,65,0,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,1,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,1,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,1,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,1,3.9,2.0,195,27,59,7.3,2.4,0.40,1
5,46,1,1.8,0.7,208,19,14,7.6,4.4,1.30,1
6,26,0,0.9,0.2,154,16,12,7.0,3.5,1.00,1
7,29,0,0.9,0.3,202,14,11,6.7,3.6,1.10,1
8,17,1,0.9,0.3,202,22,19,7.4,4.1,1.20,2
9,55,1,0.7,0.2,290,53,58,6.8,3.4,1.00,1

# 6. checking the coorelation

In [ ]:
df1.corr()

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
Age,1.000000,0.056560,0.011763,0.007529,0.080425,-0.086883,-0.019910,-0.187461,-0.265924,-0.214404,-0.137351
Gender,0.056560,1.000000,0.089291,0.100436,-0.027496,0.082332,0.080336,-0.089121,-0.093799,-0.008281,-0.082416
Total_Bilirubin,0.011763,0.089291,1.000000,0.874618,0.206669,0.214065,0.237831,-0.008099,-0.222250,-0.209775,-0.220208
Direct_Bilirubin,0.007529,0.100436,0.874618,1.000000,0.234939,0.233894,0.257544,-0.000139,-0.228531,-0.204235,-0.246046
Alkaline_Phosphotase,0.080425,-0.027496,0.206669,0.234939,1.000000,0.125680,0.167196,-0.028514,-0.165453,-0.237840,-0.184866
Alamine_Aminotransferase,-0.086883,0.082332,0.214065,0.233894,0.125680,1.000000,0.791966,-0.042518,-0.029742,-0.006805,-0.163416
Aspartate_Aminotransferase,-0.019910,0.080336,0.237831,0.257544,0.167196,0.791966,1.000000,-0.025645,-0.085290,-0.072786,-0.151934
Total_Protiens,-0.187461,-0.089121,-0.008099,-0.000139,-0.028514,-0.042518,-0.025645,1.000000,0.784053,0.231352,0.035008
Albumin,-0.265924,-0.093799,-0.222250,-0.228531,-0.165453,-0.029742,-0.085290,0.784053,1.000000,0.682893,0.161388
Albumin_and_Globulin_Ratio,-0.214404,-0.008281,-0.209775,-0.204235,-0.237840,-0.006805,-0.072786,0.231352,0.682893,1.000000,0.163506
Dataset,-0.137351,-0.082416,-0.220208,-0.246046,-0.184866,-0.163416,-0.151934,0.035008,0.161388,0.163506,1.000000

# 7. test and train

In [ ]:
x=df1[["Direct_Bilirubin"]]
y=df1[["Total_Bilirubin"]]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=2)

# 8. LinearRegression

In [ ]:

slr = LinearRegression()
slr.fit(x_train,y_train)

LinearRegression()

In [ ]:
slr.coef_

array([[1.94257255]])

In [ ]:
slr.intercept_

array([0.42867892])

In [ ]:
ypred = slr.predict(x_test)
ypred

array([[ 0.81719343],
       [15.19223032],
       [ 0.81719343],
       [10.53005619],
       [ 2.56550873],
       [ 9.1702554 ],
       [ 8.19896913],
       [ 0.81719343],
       [ 1.01145068],
       [35.97775663],
       [ 4.70233853],
       [ 0.81719343],
       [ 1.01145068],
       [ 1.20570794],
       [ 3.34253775],
       [ 0.81719343],
       [ 0.62293617],
       [ 0.62293617],
       [ 0.81719343],
       [ 0.81719343],
       [ 1.01145068],
       [ 1.98273696],
       [ 1.20570794],
       [ 0.81719343],
       [ 0.81719343],
       [16.94054561],
       [ 0.62293617],
       [ 0.81719343],
       [ 0.81719343],
       [ 0.62293617],
       [ 2.56550873],
       [ 2.95402324],
       [ 1.20570794],
       [ 1.39996519],
       [11.11282796],
       [ 0.81719343],
       [ 0.62293617],
       [ 0.62293617],
       [ 1.98273696],
       [ 1.59422245],
       [ 3.536795  ],
       [ 0.62293617],
       [ 6.64491109],
       [ 1.98273696],
       [ 1.59422245],
       [ 1.20570794],
       [ 2.17699421],
       [ 0.62293617],
       [ 3.73105226],
       [ 1.98273696],
       [ 0.81719343],
       [ 0.81719343],
       [ 2.37125147],
       [ 1.20570794],
       [ 1.98273696],
       [20.63143346],
       [ 1.20570794],
       [ 0.81719343],
       [ 0.62293617],
       [ 6.06213932],
       [ 1.7884797 ],
       [15.19223032],
       [ 0.81719343],
       [ 0.81719343],
       [ 1.59422245],
       [ 1.59422245],
       [12.08411423],
       [ 4.11956677],
       [ 1.39996519],
       [ 0.81719343],
       [ 0.81719343],
       [ 0.81719343],
       [ 0.81719343],
       [ 1.98273696],
       [ 1.01145068],
       [ 0.81719343],
       [ 0.81719343],
       [ 2.17699421],
       [ 0.62293617],
       [ 1.7884797 ],
       [ 2.95402324],
       [22.37974876],
       [ 0.81719343],
       [ 1.20570794],
       [ 0.81719343],
       [ 0.81719343],
       [ 1.01145068],
       [ 0.81719343],
       [ 1.01145068],
       [ 0.81719343],
       [ 0.81719343],
       [ 1.01145068],
       [ 1.01145068],
       [ 1.01145068],
       [ 1.20570794],
       [ 1.01145068],
       [ 0.81719343],
       [ 0.81719343],
       [ 0.81719343],
       [ 0.81719343],
       [ 0.62293617],
       [ 1.7884797 ],
       [ 2.75976598],
       [ 3.14828049],
       [ 1.98273696],
       [ 0.81719343],
       [ 0.81719343],
       [ 1.01145068],
       [ 0.81719343],
       [ 0.81719343],
       [ 4.50808128],
       [ 1.39996519],
       [ 2.75976598],
       [23.35103504],
       [ 1.98273696],
       [ 3.536795  ],
       [ 0.62293617]])

# Accuracy score

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,ypred)

0.9816171373660078

In [ ]:
predictions = slr.predict(x_test)

# predictions
 does the person have liver disease or not

In [ ]:
for i in range(10):
    result = predictions[i]
    if result == 1:
        print(f"Person {i+1}: Has Liver Disease")
    else:
        print(f"Person {i+1}: Does NOT have Liver Disease")

Person 1: Does NOT have Liver Disease
Person 2: Does NOT have Liver Disease
Person 3: Does NOT have Liver Disease
Person 4: Does NOT have Liver Disease
Person 5: Does NOT have Liver Disease
Person 6: Does NOT have Liver Disease
Person 7: Does NOT have Liver Disease
Person 8: Does NOT have Liver Disease
Person 9: Does NOT have Liver Disease
Person 10: Does NOT have Liver Disease

# 9. multiple LinearRegression

In [ ]:
x=df1[["Direct_Bilirubin", "Gender"]]
y=df1.Total_Bilirubin

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression()

In [ ]:
mlr.coef_

array([1.94132926, 0.07779788])

In [ ]:
mlr.intercept_

np.float64(0.37196931289885393)

In [ ]:
ypred = mlr.predict(x_test)
ypred

array([ 0.83803304, 15.20386953,  0.83803304, 10.54467932,  2.50743149,
        9.18574884,  8.21508421,  0.76023516,  0.95436809, 35.97609257,
        4.64289368,  0.83803304,  1.03216597,  1.22629889,  3.36176107,
        0.83803304,  0.64390011,  0.56610224,  0.83803304,  0.76023516,
        1.03216597,  2.00283059,  1.14850102,  0.83803304,  0.83803304,
       16.95106586,  0.64390011,  0.83803304,  0.83803304,  0.64390011,
        2.58522937,  2.97349522,  1.22629889,  1.42043182, 11.12707809,
        0.83803304,  0.64390011,  0.56610224,  2.00283059,  1.61456474,
        3.555894  ,  0.64390011,  6.66202081,  2.00283059,  1.61456474,
        1.22629889,  2.19696352,  0.64390011,  3.75002692,  2.00283059,
        0.83803304,  0.83803304,  2.39109644,  1.22629889,  2.00283059,
       20.63959145,  1.22629889,  0.83803304,  0.56610224,  6.07962203,
        1.73089979, 15.20386953,  0.76023516,  0.76023516,  1.53676687,
        1.61456474, 12.09774272,  4.13829277,  1.42043182,  0.83803304,
        0.76023516,  0.76023516,  0.83803304,  2.00283059,  1.03216597,
        0.76023516,  0.83803304,  2.19696352,  0.64390011,  1.73089979,
        2.89569735, 22.38678778,  0.83803304,  1.22629889,  0.83803304,
        0.83803304,  1.03216597,  0.83803304,  1.03216597,  0.83803304,
        0.83803304,  0.95436809,  0.95436809,  1.03216597,  1.22629889,
        1.03216597,  0.76023516,  0.83803304,  0.83803304,  0.76023516,
        0.56610224,  1.80869767,  2.7793623 ,  3.16762815,  1.92503272,
        0.83803304,  0.83803304,  1.03216597,  0.76023516,  0.83803304,
        4.44876075,  1.42043182,  2.7793623 , 23.27965453,  2.00283059,
        3.555894  ,  0.64390011])

In [ ]:
r2= r2_score(y_test,ypred)
print("R^2 score:", r2)

R^2 score: 0.9813642295301679

In [ ]:
import warnings
warnings.simplefilter("ignore")

xnew = np.array([[5000,2]])
prediction = mlr.predict(xnew)
print("prediction:",prediction)

prediction: [9707.17384284]

# 10.KNeighborsClassifier

In [ ]:
x=df1[['Age','Gender','Direct_Bilirubin','Alkaline_Phosphotase','Alamine_Aminotransferase','Aspartate_Aminotransferase','Total_Protiens','Albumin','Albumin_and_Globulin_Ratio','Dataset']]
y = df1['Total_Bilirubin'].astype(int)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import warnings
warnings.filterwarnings("ignore")
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(xtrain,ytrain)

KNeighborsClassifier()

In [ ]:
ypred = knn.predict(xtest)
print(ypred)

[ 0  1  1  2  0  0  0  0  0  0  0  0  0  0  0  1  0  0  2  1  1  1  0  0
  2  1  0  2  0  0  1  0  0  1  0  0  1  0  0  0  0  0  1  1  0  3  0  0
  0  7  0  1  1  0  0  0  1  0  0  0  2  0  0  1  0  0  0  2  0  2  0  2
  0  0  0  0  0  0  0  0  0  1  0  0  0  1  0  0  2  0  1  0  0 11  0  1
  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  2  0  0  0  0  0]

In [ ]:
from sklearn.metrics import classification_report, accuracy_score
print(accuracy_score(ytest,ypred))

0.42735042735042733

# 11. SVM

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVR
x=df1[['Direct_Bilirubin','Gender']].values
y=df1.Total_Bilirubin.astype(int)
xtn, xtt, ytn, ytt = train_test_split(x,y, test_size = 0.2)

In [ ]:
from sklearn.svm import LinearSVC

import warnings
warnings.simplefilter("ignore")

r = LinearSVC()
r.fit(xtn, ytn)

LinearSVC()

In [ ]:
ypd = r.predict(xtt)

In [ ]:
from sklearn.metrics import r2_score

r2 = r2_score(ytt, ypd)
print("R2 Score:", r2)

R2 Score: 0.7575483091787439

In [ ]:
from sklearn.metrics import accuracy_score
y_pred = r.predict(xtt)
print("Test Accuracy=", accuracy_score(ytt, y_pred))

Test Accuracy= 0.6666666666666666

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(ytt, y_pred))

[[63  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 8 15  1  0  0  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0]]

# 12. SVC

In [ ]:
from sklearn.svm import LinearSVC, SVC

x = df1.iloc[:,0:5] # selecting x
y = df1.Total_Bilirubin.astype(int)

lin_svc = LinearSVR().fit(x,y)

In [ ]:
rbf_svc = SVC(kernel='rbf').fit(x,y)
poly_svc3= SVC(kernel='poly',degree=3).fit(x,y)
poly_svc4= SVC(kernel='poly',degree=4).fit(x,y)

In [ ]:
print("SVC Linear Score:", lin_svc.score(x,y))
print("RBF SVC Score:",rbf_svc.score(x,y))
print("3 Degree polynomial SVC Score:", poly_svc3.score(x,y))
print("4 Degree polynomial SVC Score:", poly_svc4.score(x,y))

SVC Linear Score: 0.9953549398275673
RBF SVC Score: 0.483704974271012
3 Degree polynomial SVC Score: 0.48027444253859347
4 Degree polynomial SVC Score: 0.4957118353344768

# 13.decision tree

In [ ]:
x=df1[['Age','Gender','Direct_Bilirubin','Alkaline_Phosphotase','Alamine_Aminotransferase','Aspartate_Aminotransferase','Total_Protiens','Albumin','Albumin_and_Globulin_Ratio','Dataset']]
y = df1['Total_Bilirubin'].astype(int)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(x,y)

DecisionTreeClassifier()

In [ ]:
ypred = clf.predict(x)

In [ ]:
ypred

array([ 0, 10,  7,  1,  3,  1,  0,  0,  0,  0,  0,  2,  0,  1,  0,  0,  1,
        1,  0,  0,  2,  2,  6,  1,  0,  4,  4,  6,  1,  0,  4,  0,  1,  2,
        2,  1,  0, 14,  1,  2,  2,  0,  6,  2,  1,  1,  3,  1,  0, 18,  0,
        0,  3,  1,  8,  8,  0,  0,  0,  1,  0,  1,  1,  0,  1,  1,  2,  1,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  2,  1,  0,  2,  0,
        1,  0,  0,  0,  4,  5,  6,  8,  5,  5,  0,  3,  6,  0,  0,  0,  0,
        0,  0,  0,  5,  5,  0,  0,  0,  0,  3,  1,  0,  5,  7,  0, 12, 15,
       18, 23, 22,  1,  0,  0,  1,  5,  3,  1,  2,  3,  0,  0,  0,  1, 11,
        4,  0,  0,  0,  0,  4,  1,  1,  3,  0,  2,  0,  0,  0,  1,  1,  0,
        0,  5,  8,  0,  0,  0,  1, 11, 11,  5,  1,  1,  4, 75,  3, 22,  8,
        1,  1, 14,  0,  0,  0,  0, 14, 10,  8,  2,  2,  1,  0,  1,  1,  3,
        2,  1,  0,  6,  5,  2,  1,  2,  2,  2,  0,  0, 27,  0,  0,  0,  1,
        0,  2,  3,  3,  0,  0,  0,  2,  2,  0,  1,  0,  0,  1,  0,  0,  0,
        0,  0,  1,  1,  0,  1,  0,  1,  0,  1,  0,  2,  2,  0,  1,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1,  2,  0,  1,  0,  0,
        1,  0,  0,  0, 30, 16,  1,  0,  0,  0,  0,  1,  0, 14,  0,  0,  0,
       18,  0,  1,  1,  0,  2,  2,  1,  0,  0,  0,  1,  0,  1,  0,  1,  1,
        4,  1,  0,  0,  1,  2,  0,  0,  0,  1,  0,  0,  0,  1,  0,  0,  1,
        1,  0,  0,  1,  0, 23,  1,  0,  2,  0,  0,  0,  3,  0,  0,  0,  1,
        0,  2,  0,  1,  3,  0,  0,  2,  1,  7,  0,  0,  0,  6,  2,  1,  1,
        0,  0,  0,  3,  0,  2,  0,  0,  1,  0,  1,  1,  0,  1,  0,  1,  0,
        2,  0,  0,  0,  0,  1,  0,  0,  0,  0,  2,  0,  0, 22,  0,  0,  0,
        0,  3,  0,  0,  0,  0,  1,  0,  0,  1,  3,  0,  2,  0,  0,  0,  0,
        0,  7,  2,  1,  0,  1,  1,  0,  1,  0,  7,  0,  0,  0,  0,  0,  1,
        2,  5,  1,  2,  4,  0,  1,  1,  0,  0,  4,  8, 10,  1,  1,  1,  0,
        0,  1,  0,  0,  1,  0,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,  2,
        7,  0,  0,  0,  0, 23,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0,  6,
        1,  2,  0,  0,  0,  0,  0,  0,  1,  1,  0,  1,  0,  0,  1,  2,  2,
        0,  0,  7,  3,  0,  2,  1,  0,  5,  6,  0,  0,  0,  0,  0,  1,  1,
        0,  0,  0,  1,  2,  1,  3,  2,  2,  0, 19, 30, 32, 17,  0, 18, 20,
        0,  2,  1,  0,  1,  3,  0,  0,  2, 26,  1,  4,  0,  0,  0,  0,  9,
        3,  1,  3,  1, 30,  0,  1,  1, 19, 15,  0,  1,  0,  0,  0,  0,  1,
        5,  0, 20, 27, 11,  2,  3,  1,  0, 10,  1,  0,  0,  2,  4, 42, 15,
       16, 17,  1,  0, 22,  1,  2, 16,  7,  2,  1, 15,  3, 12, 25, 15, 12,
        0,  0,  0,  1,  1])

In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(y,ypred)
print("R2 score:", r2)

R2 score: 1.0